{% set version = "2.0.4" %}
{% set variant = "openblas" %}

package:
  name: bob.math
  version: {{ version }}

source:
  fn: bob.math-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.math/bob.math-{{ version }}.zip
  md5: b4dedfa0677ce5f782103e7114673311

build:
  number: 0
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
  - python
  - setuptools
  - bob.core
  - boost 1.61.*
  - cmake
  - numpy x.x
  - blas 1.1 {{ variant }}
  - openblas 0.2.18*
  - pkg-config

  run:
  - python
  - bob.core
  - boost 1.61.*
  - numpy x.x
  - blas 1.1 {{ variant }}
  - openblas 0.2.18*

test:
  requires:
  - nose

  imports:
  - bob
  - bob.math

  commands:
  - nosetests -sv bob.math

about:
  home: http://github.com/bioidiap/bob.math
  license: Modified BSD License (3-clause)
  summary: LAPACK and BLAS interfaces for Bob

extra:
  recipe-maintainers:
  - 183amir
